<?php

class ProjectTableSeeder extends Seeder {

    public function run()
    {
        DB::table('project')->delete();


        $pro = array(
            array(
                'name'          => 'Limpiemos la ciudad',
                'description'   => 'Este proyecto consiste en ayudar a que la ciudad esté más limpia.',
                'address'       => 'C/ de Toledo 15',
                'city'          => 'Madrid',
                'zipcode'       => '28005',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2016,11,17)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2016,12,3)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','eat')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/limpieza.jpg',
            ),
            array(
                'name'          => 'Campo de futbol para la barriada de Los Candelabros',
                'description'   => 'Este proyecto consiste en ayudar en la construcción de un campo de futbol para los niños.',
                'address'       => 'C/ de Toledo 15',
                'city'          => 'Madrid',
                'zipcode'       => '28005',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2016,11,17)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2016,12,3)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','eat')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/futbol.jpg',
            ),
            array(
                'name'          => 'Ayuda en Togo',
                'description'   => 'Este proyecto consiste en la construcción de una escuela en la capital de Togo.',
                'address'       => 'Avenue de la Chance',
                'city'          => 'Lomé',
                'zipcode'       => '526',
                'country'       => 'Togo',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2015,7,23)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2015,12,23)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','steps')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/togo.png',
            ),
            array(
                'name'          => 'Ayudemos a los elefantes',
                'description'   => 'Este proyecto trata de conseguir que se dejen de cazar elefantes de manera ilegal.',
                'address'       => 'The David Sheldrick Wildlife Trust',
                'city'          => 'Nairobi',
                'zipcode'       => '275',
                'country'       => 'Kenia',
                'maxVolunteers' => 200,
                'startDate'     => \Carbon\Carbon::createFromDate(2015,7,30)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2015,8,15)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','elephant')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/elep.jpg',
            ),
            array(
                'name'          => 'Contra la pobreza en Adama',
                'description'   => 'En este proyecto se seguirá con la labor de construcción de una insfraestructura sostenible para la ciudad.',
                'address'       => 'Aisha St.',
                'city'          => 'Adama',
                'zipcode'       => '985',
                'country'       => 'Etiopía',
                'maxVolunteers' => 75,
                'startDate'     => \Carbon\Carbon::createFromDate(2016,1,23)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2016,2,10)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','eat')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/pobreza.jpg',
            ),
            array(
                'name'          => 'Contra la tala masiva de árboles en el amazonas',
                'description'   => 'En este proyecto se aportará un granito de arena en la lucha contra la deforestación del amazonas.',
                'address'       => 'Selva del Amazonas',
                'city'          => 'Amazonia',
                'zipcode'       => '658',
                'country'       => 'Brasil',
                'maxVolunteers' => 40,
                'startDate'     => \Carbon\Carbon::createFromDate(2015,9,5)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2015,10,10)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','greenone')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/arbol.jpg',
            ),
            array(
                'name'          => 'Conservación del medio ambiente',
                'description'   => 'Este proyecto consiste en plantación de árboles.',
                'address'       => 'Avda. Bellavista',
                'city'          => 'Vejer de la Frontera',
                'zipcode'       => '11150',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2015,11,17)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2015,12,3)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','greenone')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/medioambiente.jpg',
            ),
            array(
                'name'          => 'Comedor social en Madrid',
                'description'   => 'Este proyecto consiste en la construcción de un comedor social en Madrid.',
                'address'       => 'C/ de Toledo 15',
                'city'          => 'Madrid',
                'zipcode'       => '28005',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2014,11,17)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2014,12,3)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => Ngo::where('user_id','=',User::where('username','=','eat')->first()->id)->first()->id,
                'company_id'    => null,
                'image'=> '/logos/testlogos/comedor.jpg',
            ),
            array(
                'name'          => 'La educación no entiende de edad',
                'description'   => 'Este proyecto consiste en impartir clases a personas de la tercera edad.',
                'address'       => 'Avda de la Paz',
                'city'          => 'Sevilla',
                'zipcode'       => '41013',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2014,4,12)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2014,12,26)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','boliri')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/ensenando.jpg',
            ),
            array(
                'name'          => 'Di no a las drogas',
                'description'   => 'Esta acción de RSC trata de informar a los jóvenes sobre las consecuencias de tomar drogas.',
                'address'       => 'C/ Guadalbullón, 11',
                'city'          => 'Sevilla',
                'zipcode'       => '41013',
                'country'       => 'España',
                'maxVolunteers' => 5,
                'startDate'     => \Carbon\Carbon::createFromDate(2015,6,30)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2015,7,2)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','chaos')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/drogas.jpg',
            ),
            array(
                'name'          => 'Ayuda a un mayor',
                'description'   => 'En este proyecto se ayudará a personas mayores a familiarizarse con el uso de un smartphone.',
                'address'       => 'C/ Utrera nº25',
                'city'          => 'Los Molares',
                'zipcode'       => '41750',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2015,6,20)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2015,6,22)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','xorysoft')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/mayores.jpg',
            ),
            array(
                'name'          => 'Salvemos al ciervo rojo',
                'description'   => 'Este proyecto trata de conseguir el aumento de la población de ciervo rojo.',
                'address'       => 'C/ Cruz',
                'city'          => 'Fuentes de León',
                'zipcode'       => '06280',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2016,2,25)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2016,3,10)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','boliri')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/animales.jpg',
            ),
            array(
                'name'          => 'Prevención de la violencia',
                'description'   => 'Por desgracia, los problemas de violencia con arma blanca son cada vez más comunes.
                                    Este proyecto trata de concienciar a la juventud de que no es el camino correcto.',
                'address'       => 'C/ Puerta Osario',
                'city'          => 'Bormujos',
                'zipcode'       => '41930',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2017,5,10)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2017,6,10)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','xeilaale')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/navajas.jpg',
            ),
            array(
                'name'          => 'Por una ciudad más accesible para todos',
                'description'   => 'Este proyecto consiste en la mejora de las medidas de accesibilidad para personas con movilidad reducida.',
                'address'       => 'Avda de las Ciencias',
                'city'          => 'Sevilla',
                'zipcode'       => '41020',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2016,7,12)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2016,8,26)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','jaylodet')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/accesibilidad.jpg',
            ),
            array(
                'name'          => 'Defendiendo a los más necesitados',
                'description'   => 'Este proyecto consiste en la construcción de un hogar de acogida para las personas más necesitadas.',
                'address'       => 'Avda de la Paz',
                'city'          => 'Sevilla',
                'zipcode'       => '41013',
                'country'       => 'España',
                'maxVolunteers' => 100,
                'startDate'     => \Carbon\Carbon::createFromDate(2016,4,12)->toDateTimeString(),
                'finishDate'    => \Carbon\Carbon::createFromDate(2016,12,26)->toDateTimeString(),
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime,
                'ngo_id'        => null,
                'company_id'    => Company::where('user_id','=',User::where('username','=','jaylodet')->first()->id)->first()->id,
                'image'=> '/logos/testlogos/hogar.jpg',
            ),

        );

        DB::table('project')->insert( $pro );
    }

}
