<?php

class UsersTableSeeder extends Seeder {

    public function run()
    {
        DB::table('users')->delete();


        $users = array(
            array(
                'username'      => 'admin',
                'email'      => 'admin1@piecebypeace.com',
                'password'   => Hash::make('admin1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),

            array(
                'username'      => 'manu',
                'email'      => 'manu@gmail.com',
                'password'   => Hash::make('manu1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'maria',
                'email'      => 'maria@gmail.com',
                'password'   => Hash::make('maria1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'carlos',
                'email'      => 'carlos@gmail.com',
                'password'   => Hash::make('carlos1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'jose',
                'email'      => 'jose@gmail.com',
                'password'   => Hash::make('jose1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'marta',
                'email'      => 'marta@gmail.com',
                'password'   => Hash::make('marta1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'fernando',
                'email'      => 'fernando@gmail.com',
                'password'   => Hash::make('fernando1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'antonio',
                'email'      => 'antonio@gmail.com',
                'password'   => Hash::make('antonio1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'rafael',
                'email'      => 'rafael@gmail.com',
                'password'   => Hash::make('rafael1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'juan',
                'email'      => 'juan@gmail.com',
                'password'   => Hash::make('juan1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'raquel',
                'email'      => 'raquel@gmail.com',
                'password'   => Hash::make('raquel1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'xorysoft',
                'email'      => 'xorysoft@gmail.com',
                'password'   => Hash::make('xorysoft1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'xeilaale',
                'email'      => 'xeilaale@gmail.com',
                'password'   => Hash::make('xeilaale1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'boliri',
                'email'      => 'boliri@gmail.com',
                'password'   => Hash::make('boliri1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'jaylodet',
                'email'      => 'jaylodet@gmail.com',
                'password'   => Hash::make('jaylodet1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'chaos',
                'email'      => 'chaos@gmail.com',
                'password'   => Hash::make('chaos1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'greenone',
                'email'      => 'greenone@gmail.com',
                'password'   => Hash::make('greenone1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'eat',
                'email'      => 'eat@gmail.com',
                'password'   => Hash::make('eat1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'elephant',
                'email'      => 'elephant@gmail.com',
                'password'   => Hash::make('elephant1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'send',
                'email'      => 'send@gmail.com',
                'password'   => Hash::make('send1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
            array(
                'username'      => 'steps',
                'email'      => 'steps@gmail.com',
                'password'   => Hash::make('steps1'),
                'confirmed'   => 1,
                'confirmation_code' => md5(microtime().Config::get('app.key')),
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ),
        );

        DB::table('users')->insert( $users );
    }

}
